stages:
  - test
  - build
  - deploy
test:
  stage: test
  script:
    - echo "Testing the app"
    - echo $CI_JOB_STAGE
    - apk add --no-cache python py2-pip
    - pip3 install --no-cache-dir docker-compose
    - docker-compose -v
build:
  stage: build
  script:
  - ls -l
  - echo "Building the app"
  #- docker-compose build # need to be isntalled or registerd on the runner
deploy_staiging:
  stage: deploy
  only:
  - master
  script:
  - echo "Deploying the app"
  # - docker-compose up -d # need to be isntalled or registerd on the runner
  - docker-compose up --build
