stages:
  - test
  - build
  - deploy
test:
  stage: test
  script:
    - echo "Testing the app"
    - echo $CI_JOB_STAGE
build:
  stage: build
  script:
  - echo "Building the app"
  - docker-compose build
deploy_staiging:
  stage: deploy
  only:
  - master
  script:
  - echo "Deploying the app"
  - docker-compose up -d
