version: "3.9"

services:
  db:
    # image: postgres
    # image: kartoza/postgis:13.0
    image: postgis/postgis:14-3.2-alpine
    container_name: postgis
  #  image: mdillon/postgis
    #volumes:
    #  - ./postgis:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8112
#    command: python manage.py makemigrations
#    command: python manage.py migrate
    volumes:
      - .:/code
    ports:
      - "8112:8112"
    depends_on:
      - db
