version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5433"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8111
#    command: python manage.py makemigrations
#    command: python manage.py migrate
    volumes:
      - .:/code
    ports:
      - "8111:8111"
    depends_on:
      - db
