# Generated by Django 3.1.5 on 2021-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyChecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproxy',
            name='countryCode',
            field=models.CharField(blank=True, default='DE', max_length=2),
        ),
    ]
