# Generated by Django 3.1.5 on 2021-03-05 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(auto_now=True)),
                ('timestampUpdated', models.DateTimeField(auto_now=True)),
                ('protokol', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('onlineStatus', models.BooleanField(default=False)),
                ('anonymitaetsLevel', models.CharField(blank=True, max_length=14)),
                ('latenz', models.FloatField(blank=True)),
                ('speed', models.IntegerField(blank=True, default=0)),
                ('ipAdress', models.GenericIPAddressField()),
                ('port', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
