# Generated by Django 3.1.5 on 2021-03-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyCheckStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added')),
                ('checked', models.DateTimeField(blank=True, default='', verbose_name='Timestamp')),
                ('protokol', models.CharField(blank=True, max_length=16)),
                ('working', models.BooleanField(verbose_name='Bad or Good Proxy')),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampChecked', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='', max_length=254)),
                ('protokol', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, default='DE', max_length=30)),
                ('countryCode', models.CharField(blank=True, default='DE', max_length=2)),
                ('onlineStatus', models.BooleanField(default=False)),
                ('anonymitaetsLevel', models.CharField(blank=True, default='none', max_length=14)),
                ('latenz', models.FloatField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('ipAdress', models.GenericIPAddressField(default='')),
                ('port', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyStringUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlstring', models.URLField(default='', verbose_name='URL')),
                ('timestampAdded', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP-adress')),
                ('port', models.IntegerField(default=None, verbose_name='Port')),
                ('protokol', models.CharField(blank=True, max_length=16)),
                ('ProxyCheckStamp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProxyChecker.proxycheckstamp')),
            ],
        ),
        migrations.CreateModel(
            name='LoadedPrxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampChecked', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='', max_length=254)),
                ('protokol', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, default='DE', max_length=30)),
                ('countryCode', models.CharField(blank=True, default='DE', max_length=2)),
                ('onlineStatus', models.BooleanField(default=False)),
                ('anonymitaetsLevel', models.CharField(blank=True, default='none', max_length=14)),
                ('latenz', models.FloatField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('ipAdress', models.GenericIPAddressField(default='')),
                ('port', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodProxyy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProxyChecker.proxy')),
            ],
        ),
        migrations.CreateModel(
            name='GoodProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampChecked', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='', max_length=254)),
                ('protokol', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, default='DE', max_length=30)),
                ('countryCode', models.CharField(blank=True, default='DE', max_length=2)),
                ('onlineStatus', models.BooleanField(default=False)),
                ('anonymitaetsLevel', models.CharField(blank=True, default='none', max_length=14)),
                ('latenz', models.FloatField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('ipAdress', models.GenericIPAddressField(default='0.0.0.0')),
                ('port', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BadProxyy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProxyChecker.proxy')),
            ],
        ),
        migrations.CreateModel(
            name='BadProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampChecked', models.DateTimeField(null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('protokol', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('countryCode', models.CharField(blank=True, default='', max_length=2)),
                ('onlineStatus', models.BooleanField(default=False)),
                ('anonymitaetsLevel', models.CharField(blank=True, default='none', max_length=14)),
                ('latenz', models.FloatField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('ipAdress', models.GenericIPAddressField(default='')),
                ('port', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
