# Generated by Django 3.1.5 on 2021-03-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyChecker', '0002_userproxy_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproxy',
            name='country',
            field=models.CharField(blank=True, default='DE', max_length=20),
        ),
    ]
