# Generated by Django 3.1.5 on 2021-03-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyChecker', '0004_auto_20210309_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badproxy',
            name='latenz',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goodproxy',
            name='latenz',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loadedprxy',
            name='latenz',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userproxy',
            name='latenz',
            field=models.FloatField(default=0),
        ),
    ]
