# Generated by Django 3.1.5 on 2021-03-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyChecker', '0005_auto_20210309_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadedprxy',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
