# Generated by Django 3.1.5 on 2021-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyChecker', '0006_auto_20210309_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badproxy',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='goodproxy',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='loadedprxy',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userproxy',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
