# Generated by Django 3.1.5 on 2021-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyChecker', '0007_auto_20210309_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badproxy',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goodproxy',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userproxy',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
