# Generated by Django 3.1.5 on 2021-03-13 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProxyChecker', '0010_auto_20210309_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStringUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlstring', models.URLField(default='', verbose_name='Proxy-URLs')),
                ('site', models.CharField(blank=True, max_length=16)),
                ('timestampAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestampChecked', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
