# Generated by Django 3.1.5 on 2021-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('ipAdress', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('port1', models.IntegerField(blank=True, null=True)),
                ('port2', models.IntegerField(blank=True, null=True)),
                ('port3', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=45)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
